// <auto-generated />
using System;
using Controle_Financeiro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiro.Migrations
{
    [DbContext(typeof(ControleFinanceiroContext))]
    [Migration("20231023235801_newDb")]
    partial class newDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Controle_Financeiro.Models.Despesa", b =>
                {
                    b.Property<int>("Id_Despesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data_Despesa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao_Despesa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Valor_Despesa")
                        .HasColumnType("double");

                    b.HasKey("Id_Despesa");

                    b.ToTable("Tb_Despesas");
                });

            modelBuilder.Entity("Controle_Financeiro.Models.Receita", b =>
                {
                    b.Property<int>("Id_Receita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Receita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao_Receita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Valor_Receita")
                        .HasColumnType("double");

                    b.HasKey("Id_Receita");

                    b.ToTable("Tb_Receitas");
                });
#pragma warning restore 612, 618
        }
    }
}
